# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 还是夸张一点技术栈
brief-intro: C# VB 小程序 Vue
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://18487115313.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: #gaohaoyang126
facebook_username: #gaohaoyang.water
github_username:  18487115313
email: 18487115313@163.com
weibo_username: 云南腾云生态产业大数据-员工
zhihu_username:
linkedIn_username:
dribbble_username:

description_footer: 来自还是夸张一点的个人专栏

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: #hygblog
disqus_shortname: #gaohaoyang

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 552aa8d99c04e57a157ba015b317ce20
google_analytics_id: UA-72449510-4 # google 分析追踪id

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 6
port: 4001
theme: jekyll-theme-cayman
# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false
  # Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: http://www.github.com/victorvoid
      new_tab: true
      key_trigger: g
    - title: twitter
      url: http://www.twitter.com/victorvoid
      key_trigger: t
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

      # projects in header index
projects:
  - name: fluany
    url: https://github.com/fluany/fluany
  - name: vim-frontend
    url: https://github.com/victorvoid/vim-frontend
  - name: generator-capybara
    url: https://github.com/victorvoid/generator-capybara 

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
